<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE library[
<!ELEMENT library (book)*> <!--* là 0 tới nhiều-->
<!ELEMENT book (title, author, price)+> <!-- + là 1 tới nhiều-->
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]> 

<library>
    <book>
        <title>Java</title>
        <author>Nguyen</author>
        <price>200</price>
    </book>
    <book>
        <title>C#</title>
        <author>Minh</author>
        <price>300</price>
    </book>
</library>
