<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE Mobile [
    <!ELEMENT Mobile (Company, Model, Price,  Accessories)>
    <!ELEMENT Company (#PCDATA)>
    <!ELEMENT Model (#PCDATA)>
    <!ELEMENT Price (#PCDATA)>
    <!ELEMENT Accessories (#PCDATA)>
    <!ATTLIST Model Type CDATA #REQUIRED>
    <!ENTITY HP "Head Phones">
    <!ENTITY CH "Charger">
    <!ENTITY SK "Starters Kit">
]>

<!--<!DOCTYPE Mobile SYSTEM "Mobile.dtd">--> <!--(Kiểu External(ko nên xài)-->
<Mobile>
    <Company>Nokia</Company>
    <Model Type="Camera">6600</Model>
    <Price>9999</Price>
    <Accessories>&HP; with &CH; and a &SK;</Accessories>
</Mobile>
